"""initial portable schema

Revision ID: 1813dbc3e1c8
Revises: 
Create Date: 2026-08-17 10:18:48.033346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1813dbc3e1c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('passphrase_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('personas',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('archetype', sa.String(length=50), nullable=False),
    sa.Column('primary_energy', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('trigger_conditions', sa.JSON(), nullable=True),
    sa.Column('ideal_tasks', sa.JSON(), nullable=True),
    sa.Column('peak_start_time', sa.String(length=5), nullable=True),
    sa.Column('peak_end_time', sa.String(length=5), nullable=True),
    sa.Column('trough_start_time', sa.String(length=5), nullable=True),
    sa.Column('trough_end_time', sa.String(length=5), nullable=True),
    sa.Column('recovery_start_time', sa.String(length=5), nullable=True),
    sa.Column('recovery_end_time', sa.String(length=5), nullable=True),
    sa.Column('ideal_weekly_hours', sa.Float(), nullable=False),
    sa.Column('actual_weekly_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.create_index('idx_personas_archetype', ['archetype'], unique=False)
        batch_op.create_index('idx_personas_user_active', ['user_id', 'is_active'], unique=False)

    op.create_table('user_contexts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('learned_from', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='check_confidence_range'),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name='check_weight_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_contexts', schema=None) as batch_op:
        batch_op.create_index('idx_user_contexts_created', ['created_at'], unique=False)
        batch_op.create_index('idx_user_contexts_unique', ['user_id', 'context_type', 'key'], unique=True)
        batch_op.create_index('idx_user_contexts_user_type', ['user_id', 'context_type'], unique=False)
        batch_op.create_index('idx_user_contexts_weight', ['weight'], unique=False)

    op.create_table('user_feedback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('interaction_data', sa.JSON(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('feedback_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index('idx_feedback_type', ['interaction_type'], unique=False)
        batch_op.create_index('idx_feedback_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('energy_readings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('persona_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='check_energy_confidence_range'),
    sa.CheckConstraint('energy_level >= 1 AND energy_level <= 10', name='check_energy_level_range'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('energy_readings', schema=None) as batch_op:
        batch_op.create_index('idx_energy_readings_persona_time', ['persona_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_energy_readings_timestamp', ['timestamp'], unique=False)

    op.create_table('insights',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('persona_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='check_insight_confidence'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index('idx_insights_user_dismissed', ['user_id', 'dismissed'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('persona_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('energy_required', sa.Integer(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('energy_required >= 1 AND energy_required <= 5', name='check_energy_range'),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name='check_priority_range'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_due_date', ['due_date'], unique=False)
        batch_op.create_index('idx_tasks_user_completed', ['user_id', 'completed'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_user_completed')
        batch_op.drop_index('idx_tasks_due_date')

    op.drop_table('tasks')
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index('idx_insights_user_dismissed')

    op.drop_table('insights')
    with op.batch_alter_table('energy_readings', schema=None) as batch_op:
        batch_op.drop_index('idx_energy_readings_timestamp')
        batch_op.drop_index('idx_energy_readings_persona_time')

    op.drop_table('energy_readings')
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index('idx_feedback_user_time')
        batch_op.drop_index('idx_feedback_type')

    op.drop_table('user_feedback')
    with op.batch_alter_table('user_contexts', schema=None) as batch_op:
        batch_op.drop_index('idx_user_contexts_weight')
        batch_op.drop_index('idx_user_contexts_user_type')
        batch_op.drop_index('idx_user_contexts_unique')
        batch_op.drop_index('idx_user_contexts_created')

    op.drop_table('user_contexts')
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_index('idx_personas_user_active')
        batch_op.drop_index('idx_personas_archetype')

    op.drop_table('personas')
    op.drop_table('users')
    # ### end Alembic commands ###
